---
title: "chatbot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{chatbot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vkchat)
```

```{r}
devtools::load_all()
```

set API keys
```{r keys}
bigrquery::bq_auth(path = ".secrets/tributo-app-manager_sat.json")
openai_key <- Sys.getenv("OPENAI_API_KEY")
```

```{r helpers}
bq_get_dataset_schema <- function(project, dataset){

  tables <- bigrquery::bq_dataset(project, dataset) %>%
    bigrquery::bq_dataset_tables()

  tables %>%
    purrr::map_chr(~.x$table) %>%
    purrr::map(~bigrquery::bq_table(project, dataset, .x) %>% bigrquery::bq_table_meta())

}

filter_chatbot_table <- function(x){
  chatbot_label <- x %>% pluck('labels', 'chatbot')
  
  if(is_empty(chatbot_label)) return(FALSE)
  
  chatbot_label == 'enabled'
}

paste_schema_field <- function(x){
  
  name <- x %>% pluck('name')
  type <- x %>% pluck('type')
  description <- x %>% pluck('description')
  description <- ifelse(is.null(description), '', description)
  
  glue::glue('-{name}: {type} {description}')
}

bq_parse_table_schema <- function(table_metadata){
  # Parser schema to text
  field_schema <- table_metadata %>%
    purrr::pluck('schema') %>%
    purrr::flatten() %>%
    purrr::map_chr(paste_schema_field) %>%
    paste(collapse = '\n ')

  # Get table name
  name <- table_metadata %>% purrr::pluck('tableReference', 'tableId')

  # Get table description
  description <- table_metadata %>% pluck('description')

  # Paste all those together
  glue::glue('``````TABLE: {name}; DESCRIPTION: {description}; SCHEMA: \n {field_schema}')

}
```


# Create an Assistant

Get bigquery schema
```{r bq_dataset_schema}
tables_metadata <- bq_get_dataset_schema('tributo-1', 'prod_francisco_de_miranda')

chatbot_tables <- tables_metadata %>% 
  keep(filter_chatbot_table)

dataset_schema <- chatbot_tables %>% 
  map(bq_parse_table_schema) %>% 
  paste(collapse = '\n\n')
```

Promts Example
```{r example_prompts}
example_questions <- c(
  'Cual es el monto total recaudado por el impuesto municipal de actividades económicas?',
  'Cual es la declaracion media de enero 2024?',
  'Cuales son los principales deudores de la alcaldía?',
  'Cuanto es la deuda de las declaraciones de Febrero 2024?',
  'Cual es el total de recaudacion cobrada en el año actual?',
  '¿Cuál es el contribuyente con mayor porcentaje de mora?',
  'Cuanto es la deuda total por el concepto de aseo urbano?'
)

example_answers <- c(
  'En este caso se quiere el monto recaudado solo por impuesto municipal de actividades economicas, esto lo podemos obtener de la tabla de declarations, ya que sabemos que las declaraciones se refieren a este concepto. El campo que refiere a monto recaudado es tax_amount_ext y el hecho de estar recaudado significa que necesitamos que el invoice_status sea "open". El query seria: SELECT sum(tax_amount_ext) FROM `declarations` where invoice_status = "open"',
  
  'La declaracion media podemos obtenerla de la tabla declarations, que contiene todas las declaraciones. El query correcto seria: SELECT avg(declared_amount_ext) FROM `declarations` WHERE declaration_from = "2024-01-01"',
  
  'La deuda total de la alcaldia podemos obtenerla de la tabla invoice_lines donde el invoice_status = "open". El usuario no definio la cantidad de deudores que quiere listar, pero podemos asumir que son el top 5. Para listar los deudores podemos usar el partner_id. El query seria: SELECT il.partner_id, t.taxpayer_name, sum(il.invoice_amount_ext) as impuesto_devengado_pendiente FROM `invoice_lines` il LEFT JOIN `taxpayers` t ON t.partner_id = il.partner_id WHERE il.invoice_status = "open" GROUP BY il.partner_id, t.taxpayer_name ORDER BY sum(il.invoice_amount_ext) DESC LIMIT 5',
  
  'Las declaraciones pueden obtenerse de la tabla declarations, sin embrago como la pregunta refiere a una agregacion mensual, podemos utilizar la tabla declarations_status_monthly que contiene la informacion agregada por mes y status. Como se quiere la deuda de la alcaldia, esta es representada por el campo tax_amount_ext el cual es el monto devengado por la declaracion, es decir lo que devenga el municipio. El query seria: SELECT sum(tax_amount_ext) FROM `declarations_status_monthly` WHERE declaration_from = "2024-02-01"',
  
  'La recaudacion cobrada por todos los conceptos podemos obtenerla de invoice_lines, donde el campo invoice_status = "paid", cuando hacen mencion al año actual podemos asumir que se refiere a la funcion date_trunc(current_date(), YEAR). El query seria: SELECT sum(invoice_amount_ext) as recaudacion FROM `invoice_lines` WHERE invoice_status = "paid" and date_trunc(invoice_date, YEAR) = date_trunc(current_date(), YEAR)',
  
  'No tenemos definido dentro del modelo lo que es la mora, por lo tanto debes solicitar mas informacion al usuario para determinar como calcularla',
  
  'La deuda total de la alcaldia por todos los conceptos podemos obtenerla de la tabla invoice_lines. Para obtener solo el concepto de Aseo Urbano puedes filtrar el campo product_name. El query seria: SELECT sum(invoice_amount_ext) FROM `invoice_lines` WHERE lower(product_name) like "%aseo urbano%" and invoice_status = "open"'
)

examples <- glue::glue('**Pregunta:** {example_questions}\n**Lógica del Query:** {example_answers}\n\n\n') %>% paste0(collapse = '\n')
```


Set context message
```{r context}
full_context <- glue::glue(
'Eres un analista tributario que trabaja en una Alcaldia de un pais de LATAM. Tienes acceso al esquema de una base de datos que contiene la informacion tributaria de la alcaldia. 

Tienes dos tipos de respuesta a las preguntas que te hagan:

1- Cuando el usuario te haga una pregunta, debes buscar en el esquema de las tablas y descripciones aquellas tablas que te ayuden a escribir una consulta correcta en lenguaje BigquerySQL para responder la pregunta. Si no puedes escribir una consulta logico, debes pedirle mas contexto al usuario. Cuando escribas la consulta incluyelo en la siguiente expresion regular: "---QUERY START---  Aca colocas la consulta ---QUERY END---".

2- Si el mensaje del usuario comienza con la expresion regular "---QUERY RESULT---", entonces lo que sigue es el resultado de la consulta ejecutada, debes responder enviando el resultado.

Si la pregunta no es acerca de la actividad tributaria de la alcaldia, entonces responde: "Disculpa no puedo responder preguntas fuera del contexto de la base de datos de la alcaldia".

Algunos conceptos importantes a tomar en cuenta son:

- Los contribuyentes son referidos como taxpayers en la BD. 
- Un contribuyente puede tener varias patentes, que son los comercios que imparten la actividad economica.
- Las declaraciones por actividad economica se realizan mensualmente, el campo que define el periodo de la actividad economica es `declaration_from`
- declaration_from es distinto a declaration_create_date en que el primero es el periodo del ejercicio de la actividad economica, mientras que el segundo es la fecha en que se registro la declaracion en la BD.
- Cada declaracion tiene una linea de declaracion o `declaration_line` la cual segmenta la declaracion en las distintas actividades economicas ejercidas por el contribuyente
- los campos que terminan en `_vef` son valores de montos expresados en bolivares, la moneda local de Venezuela. 
- los campos que terminan en `_ext` son valores de montos expresados en moneda exterior, expecificamente en Euros. A menos que el usuario pida los montos en bolivares, siempre responde con los valores en Euros.
- Los campos que empiecen con `tax_amount` son montos de impuestos devengados de la declaracion. Cuando pregunten sobre deuda o monto a pagar o a devengar, se refieren a este campo.
- Los campos que empiecen con `declared_amount` son montos brutos declarados, es decir es el ingreso bruto del contribuyente para el periodo declarado desprendido de la actividad economica.
- Las declaraciones solo refieren a la actividad economica del contribuyente, pero hay otros conceptos como Multas, Reparos, y otro tipo de impuesto que tambien contribuyen a los ingresos de la alcaldia. Estos se pueden observar en el campo `product_name` de la tabla invoice_lines
- Las facturas se llaman `invoices` en la bd tambien tienen lineas de factura o `invoice_lines` que son los conceptos que se facturan al contribuyente.

La base de datos esta en Bigquery y las tablas son:
{dataset_schema}

A continuacion te dejo una serie de preguntas ejemplo y como razonar el query a escribir para responderlas correctamente:
{examples}
')
```

Create an assistant with custom instructions
```{r create_assistant, eval = F}
new_assistant <- httr2::request('https://api.openai.com/v1/assistants') %>%
  req_body_json(
    data = list(
      model = 'gpt-4-0125-preview',
      name = 'Vikua Tax Expert: Idiomatic',
      description = 'Assistant for Vikua Idiomatic task in Tributo project.',
      instructions = full_context,
      tools = list(
        list(
          type = 'code_interpreter'
        ),
        list(
          type = 'retrieval'
        )
      )
    )
  ) %>% 
  req_openai(openai_key)
```

# Modify assistant instructions

Get assistants available in OpenAI account
```{r get_assistans}
assistants <- httr2::request('https://api.openai.com/v1/assistants') %>% req_openai(openai_key)
assistant_id <- Sys.getenv('ASST_TAX_EXPERT') # Tax Expert Assistant
```

```{r modify_assistant_instruction, eval = F}
request('https://api.openai.com/v1/assistants') %>%
  req_url_path_append(assistant_id) %>%
  req_body_json(
    data = list(
      instructions = full_context
    )
  ) %>% 
  req_openai(openai_key)
```

# Run Idiomatic workflow 

```{r create_thread}
thread <- create_thread_openai(openai_key)
thread_id <- thread %>% pluck('id')
thread_id <- Sys.getenv('DEV_THREAD_TAX_EXPERT') # dev thread
```

```{r ask_openai}
assistant_response <- ask_openai(
  'cual es el mes con mayor procentaje de declaracion recuadada en lo que va de año?',
  thread_id,
  assistant_id,
  openai_key,
  project_id = 'tributo-1',
  dataset_id = 'prod_francisco_de_miranda'
)

assistant_response %>% clean_response()
  
```

